#include "Grid/Building.h"
#include "Grid/GridManager.h"
#include "Components/StaticMeshComponent.h"

ABuilding::ABuilding()
{
	BuildingSize = FVector2D(2, 2);
}

void ABuilding::AutoGenerateDoorways()
{
	Doorways.Empty();

	const int32 SizeX = FMath::Max(1, FMath::RoundToInt32(BuildingSize.X));
	const int32 SizeY = FMath::Max(1, FMath::RoundToInt32(BuildingSize.Y));

	const int32 CenterX = (SizeX - 1) / 2;
	const int32 CenterY = (SizeY - 1) / 2;

	Doorways.Add({FGridVector(-1, CenterY), EGridDirection::Right});
	Doorways.Add({FGridVector(SizeX, CenterY), EGridDirection::Left});
	Doorways.Add({FGridVector(CenterX, -1), EGridDirection::Down});
	Doorways.Add({FGridVector(CenterX, SizeY), EGridDirection::Up});
}

TArray<FGridVector> ABuilding::GetDoorwayWorldPositions() const
{
	TArray<FGridVector> Result;
	if (!bIsPlaced)
	{
		return Result;
	}

	for (const FBuildingDoorway& Doorway : Doorways)
	{
		Result.Add(GridPosition + Doorway.RelativePosition);
	}
	return Result;
}

void ABuilding::UpdatePreviewAppearance(const FGridVector& GridPos)
{
	if (!IsPreview() || !MeshComponent)
	{
		return;
	}

	UGridManager* GM = GetGridManager();
	if (!GM || !GM->IsGridInitialized())
	{
		return;
	}

	const float CellSize = GM->GetCellSize();
	const FVector BasePos = GM->GridToWorld(GridPos);
	const float OffsetX = CellSize * (BuildingSize.X - 1.0f) * 0.5f;
	const float OffsetY = CellSize * (BuildingSize.Y - 1.0f) * 0.5f;
	SetActorLocation(FVector(BasePos.X + OffsetX, BasePos.Y + OffsetY, BasePos.Z));

	const float RefSize = FMath::Max(ReferenceMeshSize, 1.0f);
	const float ScaleX = (BuildingSize.X * CellSize) / RefSize;
	const float ScaleY = (BuildingSize.Y * CellSize) / RefSize;
	SetActorScale3D(FVector(ScaleX, ScaleY, 1.0f));

	UMaterialInterface* Mat = IsPreviewPlacementValid() ? PreviewMaterial : InvalidPreviewMaterial;
	if (Mat)
	{
		for (int32 i = 0; i < MeshComponent->GetNumMaterials(); ++i)
		{
			MeshComponent->SetMaterial(i, Mat);
		}
	}
}

void ABuilding::UpdateBuildingAppearance()
{
	if (!MeshComponent)
	{
		return;
	}

	UGridManager* GM = GetGridManager();
	if (!GM || !GM->IsGridInitialized())
	{
		return;
	}

	const float CellSize = GM->GetCellSize();
	const FVector BasePos = GM->GridToWorld(GridPosition);
	const float OffsetX = CellSize * (BuildingSize.X - 1.0f) * 0.5f;
	const float OffsetY = CellSize * (BuildingSize.Y - 1.0f) * 0.5f;
	SetActorLocation(FVector(BasePos.X + OffsetX, BasePos.Y + OffsetY, BasePos.Z));

	const float RefSize = FMath::Max(ReferenceMeshSize, 1.0f);
	const float ScaleX = (BuildingSize.X * CellSize) / RefSize;
	const float ScaleY = (BuildingSize.Y * CellSize) / RefSize;
	SetActorScale3D(FVector(ScaleX, ScaleY, 1.0f));
}

void ABuilding::OnPlacedOnGrid_Implementation()
{
	Super::OnPlacedOnGrid_Implementation();
	UpdateBuildingAppearance();
}

void ABuilding::OnEnterPlaced_Implementation()
{
	Super::OnEnterPlaced_Implementation();
}

void ABuilding::OnPreviewValidChanged_Implementation(bool bValid)
{
}
