#include "Grid/Building.h"
#include "Grid/GridManager.h"
#include "Grid/FoundationComponent.h"
#include "Components/StaticMeshComponent.h"

ABuilding::ABuilding()
{
	BuildingSize = FVector2D(2, 2);
	PlaceableType = EPlaceableType::Building;

	FoundationComponent = CreateDefaultSubobject<UFoundationComponent>(TEXT("FoundationComponent"));
}

FGridVector ABuilding::TransformLocalPosition(const FGridVector& LocalPos) const
{
	const int32 W = FMath::Max(1, FMath::RoundToInt32(BuildingSize.X));
	const int32 H = FMath::Max(1, FMath::RoundToInt32(BuildingSize.Y));

	switch (BuildingRotation)
	{
	case EGridRotation::Rot0:
		return LocalPos;

	case EGridRotation::Rot90:
		return FGridVector(LocalPos.Y, W - 1 - LocalPos.X);

	case EGridRotation::Rot180:
		return FGridVector(W - 1 - LocalPos.X, H - 1 - LocalPos.Y);

	case EGridRotation::Rot270:
		return FGridVector(H - 1 - LocalPos.Y, LocalPos.X);

	default:
		return LocalPos;
	}
}

FVector2D ABuilding::GetEffectiveBuildingSize() const
{
	const int32 W = FMath::Max(1, FMath::RoundToInt32(BuildingSize.X));
	const int32 H = FMath::Max(1, FMath::RoundToInt32(BuildingSize.Y));

	switch (BuildingRotation)
	{
	case EGridRotation::Rot0:
	case EGridRotation::Rot180:
		return FVector2D(W, H);

	case EGridRotation::Rot90:
	case EGridRotation::Rot270:
		return FVector2D(H, W);

	default:
		return FVector2D(W, H);
	}
}

void ABuilding::AutoGenerateDoorways()
{
	Doorways.Empty();

	const int32 W = FMath::Max(1, FMath::RoundToInt32(BuildingSize.X));
	const int32 H = FMath::Max(1, FMath::RoundToInt32(BuildingSize.Y));

	const int32 CenterX = (W - 1) / 2;
	const int32 CenterY = (H - 1) / 2;

	Doorways.Add({FGridVector(0, CenterY), EGridDirection::Left});
	Doorways.Add({FGridVector(W - 1, CenterY), EGridDirection::Right});
	Doorways.Add({FGridVector(CenterX, 0), EGridDirection::Up});
	Doorways.Add({FGridVector(CenterX, H - 1), EGridDirection::Down});
}

FGridVector ABuilding::GetDoorwayConnectionPoint(const FBuildingDoorway& Doorway) const
{
	const FGridVector LocalPos = TransformLocalPosition(Doorway.RelativePosition);
	EGridDirection RotatedDir = Doorway.FacingDirection;
	for (uint8 i = 0; i < static_cast<uint8>(BuildingRotation); ++i)
	{
		switch (RotatedDir)
		{
		case EGridDirection::Up:    RotatedDir = EGridDirection::Left; break;
		case EGridDirection::Left:  RotatedDir = EGridDirection::Down; break;
		case EGridDirection::Down:  RotatedDir = EGridDirection::Right; break;
		case EGridDirection::Right: RotatedDir = EGridDirection::Up; break;
		default: break;
		}
	}
	const FGridVector DirVec = GridDirectionUtils::GetVector(RotatedDir);
	return GridPosition + LocalPos + DirVec;
}

FGridVector ABuilding::GetDoorwayConnectionPointForPosition(const FBuildingDoorway& Doorway, const FGridVector& BasePos) const
{
	const FGridVector LocalPos = TransformLocalPosition(Doorway.RelativePosition);
	EGridDirection RotatedDir = Doorway.FacingDirection;
	for (uint8 i = 0; i < static_cast<uint8>(BuildingRotation); ++i)
	{
		switch (RotatedDir)
		{
		case EGridDirection::Up:    RotatedDir = EGridDirection::Left; break;
		case EGridDirection::Left:  RotatedDir = EGridDirection::Down; break;
		case EGridDirection::Down:  RotatedDir = EGridDirection::Right; break;
		case EGridDirection::Right: RotatedDir = EGridDirection::Up; break;
		default: break;
		}
	}
	const FGridVector DirVec = GridDirectionUtils::GetVector(RotatedDir);
	return BasePos + LocalPos + DirVec;
}

TArray<FGridVector> ABuilding::GetDoorwayWorldPositions() const
{
	TArray<FGridVector> Result;
	if (!bIsPlaced)
	{
		return Result;
	}

	for (const FBuildingDoorway& Doorway : Doorways)
	{
		Result.Add(GetDoorwayConnectionPoint(Doorway));
	}
	return Result;
}

bool ABuilding::HasDoorwayAt(const FGridVector& WorldPos) const
{
	for (const FBuildingDoorway& Doorway : Doorways)
	{
		if (GetDoorwayConnectionPoint(Doorway) == WorldPos)
		{
			return true;
		}
	}
	return false;
}

TArray<FGridVector> ABuilding::CalculateOccupiedCells(const FGridVector& BasePos) const
{
	TArray<FGridVector> Cells;
	const FVector2D EffSize = GetEffectiveBuildingSize();
	const int32 EX = FMath::Max(1, FMath::RoundToInt32(EffSize.X));
	const int32 EY = FMath::Max(1, FMath::RoundToInt32(EffSize.Y));

	for (int32 Y = 0; Y < EY; ++Y)
	{
		for (int32 X = 0; X < EX; ++X)
		{
			Cells.Add(FGridVector(BasePos.X + X, BasePos.Y + Y));
		}
	}

	return Cells;
}

bool ABuilding::ValidatePlacement(const FGridVector& BasePos) const
{
	UGridManager* GM = GetGridManager();
	if (!GM || !GM->IsGridInitialized())
	{
		return false;
	}

	for (const FBuildingDoorway& Doorway : Doorways)
	{
		const FGridVector ConnPt = GetDoorwayConnectionPointForPosition(Doorway, BasePos);

		// doorway 连接点必须在 grid 范围内
		if (!GM->IsValidGridPos(ConnPt))
		{
			return false;
		}

		// doorway 连接点不能被其他 building 占据
		const FGridCell& Cell = GM->GetCell(ConnPt);
		if (Cell.Type == ECellType::Building)
		{
			return false;
		}
	}

	return true;
}

void ABuilding::UpdatePreviewAppearance(const FGridVector& GridPos)
{
	if (!IsPreview() || !MeshComponent)
	{
		return;
	}

	UGridManager* GM = GetGridManager();
	if (!GM || !GM->IsGridInitialized())
	{
		return;
	}

	const float CellSize = GM->GetCellSize();
	const FVector2D EffSize = GetEffectiveBuildingSize();
	const FVector BasePos = GM->GridToWorld(GridPos);
	const float OffsetX = CellSize * (EffSize.X - 1.0f) * 0.5f;
	const float OffsetY = CellSize * (EffSize.Y - 1.0f) * 0.5f;
	SetActorLocation(FVector(BasePos.X + OffsetX, BasePos.Y + OffsetY, BasePos.Z));

	const float RefSize = FMath::Max(ReferenceMeshSize, 1.0f);
	const float ScaleX = (EffSize.X * CellSize) / RefSize;
	const float ScaleY = (EffSize.Y * CellSize) / RefSize;
	SetActorScale3D(FVector(ScaleX, ScaleY, 1.0f));

	const float Yaw = static_cast<float>(static_cast<uint8>(BuildingRotation)) * 90.0f;
	SetActorRotation(FRotator(0.0f, Yaw, 0.0f));

	UMaterialInterface* Mat = IsPreviewPlacementValid() ? PreviewMaterial : InvalidPreviewMaterial;
	if (Mat)
	{
		for (int32 i = 0; i < MeshComponent->GetNumMaterials(); ++i)
		{
			MeshComponent->SetMaterial(i, Mat);
		}
	}
}

void ABuilding::UpdateBuildingAppearance()
{
	if (!MeshComponent)
	{
		return;
	}

	UGridManager* GM = GetGridManager();
	if (!GM || !GM->IsGridInitialized())
	{
		return;
	}

	const float CellSize = GM->GetCellSize();
	const FVector2D EffSize = GetEffectiveBuildingSize();
	const FVector BasePos = GM->GridToWorld(GridPosition);
	const float OffsetX = CellSize * (EffSize.X - 1.0f) * 0.5f;
	const float OffsetY = CellSize * (EffSize.Y - 1.0f) * 0.5f;
	SetActorLocation(FVector(BasePos.X + OffsetX, BasePos.Y + OffsetY, BasePos.Z));

	const float RefSize = FMath::Max(ReferenceMeshSize, 1.0f);
	const float ScaleX = (EffSize.X * CellSize) / RefSize;
	const float ScaleY = (EffSize.Y * CellSize) / RefSize;
	SetActorScale3D(FVector(ScaleX, ScaleY, 1.0f));

	const float Yaw = static_cast<float>(static_cast<uint8>(BuildingRotation)) * 90.0f;
	SetActorRotation(FRotator(0.0f, Yaw, 0.0f));
}

void ABuilding::OnPlacedOnGrid_Implementation()
{
	Super::OnPlacedOnGrid_Implementation();
	UpdateBuildingAppearance();

	SpawnDebugDoorways();

	UGridManager* GM = GetGridManager();
	if (GM)
	{
		for (const FGridVector& Cell : OccupiedCells)
		{
			TArray<FGridVector> Neighbors = GM->GetNeighbors(Cell, true);
			for (const FGridVector& N : Neighbors)
			{
				if (GM->GetCellType(N) == ECellType::Road)
				{
					GM->OnCellChanged.Broadcast(N, GM->GetCell(N));
				}
			}
		}

		GM->OnCellChanged.AddDynamic(this, &ABuilding::OnDoorwayCellChanged);
	}

	RefreshFoundation();
}

void ABuilding::OnRemovedFromGrid_Implementation()
{
	UGridManager* GM = GetGridManager();
	if (GM)
	{
		GM->OnCellChanged.RemoveDynamic(this, &ABuilding::OnDoorwayCellChanged);
	}

	if (FoundationComponent)
	{
		FoundationComponent->ClearFoundation();
	}
	DestroyDebugDoorways();
	Super::OnRemovedFromGrid_Implementation();
}

void ABuilding::OnEnterPlaced_Implementation()
{
	Super::OnEnterPlaced_Implementation();

	if (UStaticMesh* CurrentMesh = MeshComponent ? MeshComponent->GetStaticMesh() : nullptr)
	{
		RestoreMeshMaterials(CurrentMesh);
	}
}

void ABuilding::OnPreviewValidChanged_Implementation(bool bValid)
{
}

void ABuilding::EnsureMeshMaterialsCached(UStaticMesh* Mesh)
{
	if (!Mesh || MeshMaterialCache.Contains(Mesh))
	{
		return;
	}

	const TArray<FStaticMaterial>& StaticMaterials = Mesh->GetStaticMaterials();
	TArray<TObjectPtr<UMaterialInterface>> Materials;
	Materials.Reserve(StaticMaterials.Num());
	for (const FStaticMaterial& SM : StaticMaterials)
	{
		Materials.Add(SM.MaterialInterface);
	}
	MeshMaterialCache.Add(Mesh, MoveTemp(Materials));
}

void ABuilding::RestoreMeshMaterials(UStaticMesh* Mesh)
{
	if (!Mesh || !MeshComponent)
	{
		return;
	}

	const TArray<TObjectPtr<UMaterialInterface>>* Cached = MeshMaterialCache.Find(Mesh);
	if (!Cached)
	{
		return;
	}

	for (int32 i = 0; i < Cached->Num(); ++i)
	{
		if ((*Cached)[i])
		{
			MeshComponent->SetMaterial(i, (*Cached)[i]);
		}
	}
}

void ABuilding::SpawnDebugDoorways()
{
	DestroyDebugDoorways();

	if (!DebugDoorwayMesh || !bIsPlaced)
	{
		return;
	}

	UGridManager* GM = GetGridManager();
	if (!GM || !GM->IsGridInitialized())
	{
		return;
	}

	for (const FBuildingDoorway& Doorway : Doorways)
	{
		const FGridVector ConnectionPoint = GetDoorwayConnectionPoint(Doorway);
		const FVector WorldPos = GM->GridToWorld(ConnectionPoint);

		UStaticMeshComponent* DebugComp = NewObject<UStaticMeshComponent>(this);
		DebugComp->SetStaticMesh(DebugDoorwayMesh);
		DebugComp->SetWorldLocation(WorldPos);
		DebugComp->SetCollisionEnabled(ECollisionEnabled::NoCollision);
		DebugComp->RegisterComponent();
		DebugComp->AttachToComponent(RootComponent, FAttachmentTransformRules::KeepWorldTransform);

		DebugDoorwayComponents.Add(DebugComp);
	}
}

void ABuilding::DestroyDebugDoorways()
{
	for (UStaticMeshComponent* Comp : DebugDoorwayComponents)
	{
		if (Comp)
		{
			Comp->DestroyComponent();
		}
	}
	DebugDoorwayComponents.Empty();
}

void ABuilding::DetermineEdgeConnections(bool& bTop, bool& bRight, bool& bBottom, bool& bLeft) const
{
	bTop = false; bRight = false; bBottom = false; bLeft = false;

	if (!bIsPlaced) return;

	UGridManager* GM = GetGridManager();
	if (!GM) return;

	const FVector2D EffSize = GetEffectiveBuildingSize();
	const int32 EffW = FMath::RoundToInt32(EffSize.X);
	const int32 EffH = FMath::RoundToInt32(EffSize.Y);

	for (const FBuildingDoorway& Doorway : Doorways)
	{
		const FGridVector ConnectionPoint = GetDoorwayConnectionPoint(Doorway);
		const ECellType CellType = GM->GetCellType(ConnectionPoint);
		if (CellType != ECellType::Road)
		{
			continue;
		}

		const FGridVector Local = TransformLocalPosition(Doorway.RelativePosition);

		if (Local.Y == 0)
		{
			bTop = true;
		}
		else if (Local.X == EffW - 1)
		{
			bRight = true;
		}
		else if (Local.Y == EffH - 1)
		{
			bBottom = true;
		}
		else if (Local.X == 0)
		{
			bLeft = true;
		}
	}
}

void ABuilding::RefreshFoundation()
{
	if (!FoundationComponent || !bIsPlaced)
	{
		return;
	}

	UGridManager* GM = GetGridManager();
	if (!GM || !GM->IsGridInitialized())
	{
		return;
	}

	const FVector2D EffSize = GetEffectiveBuildingSize();
	const float CellSize = GM->GetCellSize();

	bool bTop, bRight, bBottom, bLeft;
	DetermineEdgeConnections(bTop, bRight, bBottom, bLeft);

	FoundationComponent->BuildFoundation(EffSize.X, EffSize.Y, CellSize,
		bTop, bRight, bBottom, bLeft);
}

void ABuilding::OnDoorwayCellChanged(FGridVector CellPos, const FGridCell& NewCell)
{
	TArray<FGridVector> DoorwayPositions = GetDoorwayWorldPositions();
	if (DoorwayPositions.Contains(CellPos))
	{
		RefreshFoundation();
	}
}
