#pragma once

#include "CoreMinimal.h"
#include "Grid/MeshGridPlaceableActor.h"
#include "Building.generated.h"

class UFoundationComponent;

USTRUCT(BlueprintType)
struct CITYFLOW_API FBuildingDoorway
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Doorway")
	FGridVector RelativePosition;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Doorway")
	EGridDirection FacingDirection = EGridDirection::None;
};

UCLASS()
class CITYFLOW_API ABuilding : public AMeshGridPlaceableActor
{
	GENERATED_BODY()

public:
	ABuilding();

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Building")
	TArray<FBuildingDoorway> Doorways;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Building")
	bool bIsDestination = false;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Building")
	float ReferenceMeshSize = 100.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Building")
	EGridRotation BuildingRotation = EGridRotation::Rot0;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Building|Debug")
	TObjectPtr<UStaticMesh> DebugDoorwayMesh;

	UFUNCTION(BlueprintCallable, Category = "Building")
	void AutoGenerateDoorways();

	UFUNCTION(BlueprintPure, Category = "Building")
	TArray<FGridVector> GetDoorwayWorldPositions() const;

	UFUNCTION(BlueprintPure, Category = "Building")
	bool HasDoorwayAt(const FGridVector& WorldPos) const;

	UFUNCTION(BlueprintPure, Category = "Building")
	FVector2D GetEffectiveBuildingSize() const;

	UFUNCTION(BlueprintPure, Category = "Building")
	FGridVector GetDoorwayConnectionPoint(const FBuildingDoorway& Doorway) const;

	UFUNCTION(BlueprintPure, Category = "Building")
	FGridVector TransformLocalPosition(const FGridVector& LocalPos) const;

	virtual void UpdatePreviewAppearance(const FGridVector& GridPos) override;

	UFUNCTION(BlueprintCallable, Category = "Building")
	void RefreshFoundation();

protected:
	virtual void OnPlacedOnGrid_Implementation() override;
	virtual void OnEnterPlaced_Implementation() override;
	virtual void OnPreviewValidChanged_Implementation(bool bValid) override;
	virtual void OnRemovedFromGrid_Implementation() override;

	virtual TArray<FGridVector> CalculateOccupiedCells(const FGridVector& BasePos) const override;
	virtual bool ValidatePlacement(const FGridVector& BasePos) const override;

private:
	void UpdateBuildingAppearance();

	void EnsureMeshMaterialsCached(UStaticMesh* Mesh);
	void RestoreMeshMaterials(UStaticMesh* Mesh);

	void SpawnDebugDoorways();
	void DestroyDebugDoorways();

	void DetermineEdgeConnections(bool& bTop, bool& bRight, bool& bBottom, bool& bLeft) const;

	UFUNCTION()
	void OnDoorwayCellChanged(FGridVector CellPos, const FGridCell& NewCell);

	TMap<TObjectPtr<UStaticMesh>, TArray<TObjectPtr<UMaterialInterface>>> MeshMaterialCache;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Components", meta = (AllowPrivateAccess = "true"))
	TObjectPtr<UFoundationComponent> FoundationComponent;

	UPROPERTY()
	TArray<TObjectPtr<class UStaticMeshComponent>> DebugDoorwayComponents;
};
