#pragma once

#include "CoreMinimal.h"
#include "Grid/MeshGridPlaceableActor.h"
#include "Building.generated.h"

USTRUCT(BlueprintType)
struct CITYFLOW_API FBuildingDoorway
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Doorway")
	FGridVector RelativePosition;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Doorway")
	EGridDirection FacingDirection = EGridDirection::None;
};

UCLASS()
class CITYFLOW_API ABuilding : public AMeshGridPlaceableActor
{
	GENERATED_BODY()

public:
	ABuilding();

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Building")
	TArray<FBuildingDoorway> Doorways;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Building")
	bool bIsDestination = false;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Building")
	float ReferenceMeshSize = 100.0f;

	UFUNCTION(BlueprintCallable, Category = "Building")
	void AutoGenerateDoorways();

	UFUNCTION(BlueprintPure, Category = "Building")
	TArray<FGridVector> GetDoorwayWorldPositions() const;

	virtual void UpdatePreviewAppearance(const FGridVector& GridPos) override;

protected:
	virtual void OnPlacedOnGrid_Implementation() override;
	virtual void OnEnterPlaced_Implementation() override;
	virtual void OnPreviewValidChanged_Implementation(bool bValid) override;

private:
	void UpdateBuildingAppearance();

	void EnsureMeshMaterialsCached(UStaticMesh* Mesh);
	void RestoreMeshMaterials(UStaticMesh* Mesh);

	TMap<TObjectPtr<UStaticMesh>, TArray<TObjectPtr<UMaterialInterface>>> MeshMaterialCache;
};
